environment: dev
gateway:
  host: 0.0.0.0
  port: 8080
  timeout_ms: 80
  batch_max_size: 64
  batch_max_delay_ms: 5
  ab_salt: "recsys-ab-dev"
services:
  feature_url: http://localhost:8082
  candidate_url: http://localhost:8081
  reranker_url: http://localhost:8083
caching:
  user_profile_ttl_s: 300
  candidate_ttl_s: 60
observability:
  prometheus_port: 9000
